localhub/flags/urls.py
# Django
from django.urls import path

# Local
from .views import flag_delete_view, flag_list_view

app_name = "flags"


urlpatterns = [
    path("", view=flag_list_view, name="list"),
    path("<int:pk>/~delete/", view=flag_delete_view, name="delete"),
]

localhub/private_messages/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Localhub
from localhub.users.urls import user_re_path

# Local
from . import views

app_name = "private_messages"

urlpatterns = [
    path("inbox/", views.inbox_view, name="inbox"),
    path("outbox/", views.outbox_view, name="outbox"),
    path("send/", views.message_create_view, name="message_create"),
    path("~/mark-read/", views.message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", views.message_detail_view, name="message_detail"),
    path(
        "message/<int:pk>/~follow-up/",
        views.message_follow_up_view,
        name="message_follow_up",
    ),
    path("message/<int:pk>/~reply/", views.message_reply_view, name="message_reply"),
    path("message/<int:pk>/~delete/", views.message_delete_view, name="message_delete"),
    path(
        "message/<int:pk>/~read/",
        views.message_mark_read_view,
        name="message_mark_read",
    ),
    path(
        "message/<int:pk>/~bookmark/",
        views.message_bookmark_view,
        name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        views.message_remove_bookmark_view,
        name="message_remove_bookmark",
    ),
    user_re_path(
        r"~send/$",
        views.message_recipient_create_view,
        name="message_create_recipient",
    ),
]

localhub/users/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path, re_path

# Local
from . import views

app_name = "users"

USERNAME_RE = r"^(?P<username>[\w.@+-]+)/"


def user_re_path(path, *args, **kwargs):
    return re_path(USERNAME_RE + path, *args, **kwargs)


urlpatterns = [
    path("autocomplete/", views.user_autocomplete_list_view, name="autocomplete_list"),
    path("members/", views.member_list_view, name="member_list"),
    path("following/", views.following_user_list_view, name="following_list"),
    path("followers/", views.follower_user_list_view, name="follower_list"),
    path("blocked/", views.blocked_user_list_view, name="blocked_list"),
    user_re_path(r"likes/$", views.user_activity_likes_view, name="activity_likes"),
    user_re_path(
        r"likes/comments/$", views.user_comment_likes_view, name="comment_likes",
    ),
    user_re_path(
        r"mentions/$", views.user_activity_mentions_view, name="activity_mentions",
    ),
    user_re_path(
        r"mentions/comments/$",
        views.user_comment_mentions_view,
        name="comment_mentions",
    ),
    user_re_path(r"preview/$", views.user_preview_view, name="preview"),
    user_re_path(r"follow/$", views.user_follow_view, name="follow"),
    user_re_path(r"unfollow/$", views.user_unfollow_view, name="unfollow"),
    user_re_path(r"block/$", views.user_block_view, name="block"),
    user_re_path(r"unblock/$", views.user_unblock_view, name="unblock"),
    user_re_path(r"comments/$", views.user_comment_list_view, name="comments"),
    user_re_path(r"messages/$", views.user_message_list_view, name="messages"),
    user_re_path(r"$", views.user_stream_view, name="activities"),
]

localhub/users/forms.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.utils.translation import gettext_lazy as _

# Localhub
from localhub.forms import FormHelper
from localhub.forms.widgets import BaseTypeaheadInput, ClearableImageInput

# Local
from .app_settings import MENTIONS_TYPEAHEAD_CONFIG
from .validators import validate_mentions

User = get_user_model()


class MentionsTypeaheadInput(BaseTypeaheadInput):
    typeahead_configs = [MENTIONS_TYPEAHEAD_CONFIG]


class MentionsField(forms.CharField):
    widget = MentionsTypeaheadInput
    default_validators = [validate_mentions]


class UserChangeForm(BaseUserChangeForm):
    class Meta(BaseUserChangeForm.Meta):
        model = User


class UserCreationForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "name",
            "avatar",
            "bio",
            "language",
            "default_timezone",
            "send_email_notifications",
            "activity_stream_filters",
            "show_sensitive_content",
            "show_external_images",
            "show_embedded_content",
        )
        widgets = {
            "notification_preferences": forms.CheckboxSelectMultiple,
            "activity_stream_filters": forms.CheckboxSelectMultiple,
            "avatar": ClearableImageInput,
        }

        labels = {
            "send_email_notifications": _(
                "Send me an email when I receive a new Message or Notification"
            ),
            "show_external_images": _(
                "Show external images embedded in Markdown and OpenGraph content"
            ),
            "show_sensitive_content": _(
                "Show sensitive content by default in public feeds"
            ),
            "show_embedded_content": _(
                "Show embedded content such as Youtube videos and tweets"
            ),
            "default_timezone": _("Timezone"),
        }

        help_texts = {
            "activity_stream_filters": _(
                "Filters only apply to other people's activities, not your own. "
                "Filters are mutually exclusive and may cancel each other out."
            ),
            "show_sensitive_content": _(
                "You can remove sensitive content completely from your feeds by "
                "blocking the relevant tags."
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fieldsets = FormHelper(
            self,
            (
                None,
                (
                    "name",
                    "avatar",
                    "language",
                    "default_timezone",
                    "send_email_notifications",
                    "bio",
                ),
            ),
            (
                _("Content Preferences"),
                (
                    "show_sensitive_content",
                    "show_external_images",
                    "show_embedded_content",
                    "activity_stream_filters",
                ),
            ),
        )

localhub/users/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


# Django
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.template.response import TemplateResponse
from django.urls import resolve
from django.utils.functional import cached_property
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.translation import gettext_lazy as _
from django.views.generic import DeleteView, DetailView, ListView, View

# Third Party Libraries
from rules.contrib.views import PermissionRequiredMixin

# Localhub
from localhub.activities.utils import get_activity_models
from localhub.activities.views.streams import BaseActivityStreamView
from localhub.comments.models import Comment
from localhub.comments.views import BaseCommentListView
from localhub.communities.models import Membership
from localhub.communities.rules import is_member
from localhub.communities.views import CommunityRequiredMixin
from localhub.likes.models import Like
from localhub.private_messages.models import Message
from localhub.views import (
    ParentObjectMixin,
    SearchMixin,
    SuccessActionView,
    SuccessUpdateView,
)

# Local
from .forms import UserForm


class BaseUserQuerySetMixin(CommunityRequiredMixin):

    # users blocking me
    exclude_blocker_users = True

    # users I am blocking
    exclude_blocked_users = False

    # users blocking me, or whom I am blocking
    exclude_blocking_users = False

    def get_user_queryset(self):
        qs = get_user_model().objects.for_community(self.request.community)

        if self.exclude_blocking_users:
            qs = qs.exclude_blocking(self.request.user)

        elif self.exclude_blocked_users:
            qs = qs.exclude_blocked(self.request.user)

        elif self.exclude_blocker_users:
            qs = qs.exclude_blockers(self.request.user)

        return qs


class UserQuerySetMixin(BaseUserQuerySetMixin):
    def get_queryset(self):
        return self.get_user_queryset()


class MemberQuerySetMixin:
    """Includes membership details such as role and join date"""

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_role(self.request.community)
            .with_joined(self.request.community)
        )


class CurrentUserMixin(LoginRequiredMixin):
    """
    Always returns the current logged in user.
    """

    def get_object(self):
        return self.request.user


class SingleUserMixin(ParentObjectMixin, BaseUserQuerySetMixin):
    parent_slug_kwarg = "username"
    parent_slug_field = "username"
    parent_context_object_name = "user_obj"
    parent_required = False

    def get_parent_queryset(self):
        return self.get_user_queryset()

    def get(self, request, *args, **kwargs):
        if self.user_obj is None:
            return TemplateResponse(
                request,
                "users/detail/not_found.html",
                {"username": kwargs["username"]},
                status=404,
            )
        response = super().get(request, *args, **kwargs)
        if self.user_obj != request.user:
            self.user_obj.get_notifications().for_recipient(request.user).mark_read()
        return response

    @cached_property
    def user_obj(self):
        return self.get_parent_object()

    @cached_property
    def display_name(self):
        return self.user_obj.get_display_name()

    @cached_property
    def membership(self):
        return Membership.objects.filter(
            member=self.user_obj, community=self.request.community
        ).first()

    @cached_property
    def is_current_user(self):
        return self.user_obj == self.request.user

    @cached_property
    def is_blocked(self):
        return self.is_blocker or self.is_blocking

    @cached_property
    def is_following(self):
        return (
            not self.is_current_user
            and self.user_obj in self.request.user.following.all()
        )

    @cached_property
    def is_follower(self):
        return (
            not self.is_current_user
            and self.request.user in self.user_obj.following.all()
        )

    @cached_property
    def is_blocker(self):
        if self.is_current_user:
            return False
        return self.request.user.blockers.filter(pk=self.user_obj.id).exists()

    @cached_property
    def is_blocking(self):
        if self.is_current_user:
            return False
        return self.request.user.blocked.filter(pk=self.user_obj.id).exists()

    @cached_property
    def unread_messages(self):
        if self.is_current_user:
            return 0

        return (
            Message.objects.for_community(self.request.community)
            .from_sender_to_recipient(self.user_obj, self.request.user)
            .unread()
            .count()
        )

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            **{
                "is_current_user": self.is_current_user,
                "is_blocked": self.is_blocked,
                "is_blocker": self.is_blocker,
                "is_blocking": self.is_blocking,
                "is_following": self.is_following,
                "is_follower": self.is_follower,
                "display_name": self.display_name,
                "membership": self.membership,
                "unread_messages": self.unread_messages,
            },
        }


class BaseUserActivityStreamView(SingleUserMixin, BaseActivityStreamView):
    ...


class BaseUserCommentListView(SingleUserMixin, BaseCommentListView):
    ...


class UserPreviewView(MemberQuerySetMixin, UserQuerySetMixin, DetailView):
    template_name = "users/preview.html"
    context_object_name = "user_obj"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_object_url(self):
        """Allow a different object url e.g. to message or comment tabs."""
        url = self.request.GET.get("object_url")
        if url and url_has_allowed_host_and_scheme(url, settings.ALLOWED_HOSTS):
            try:
                resolve(url)
                return url
            except Http404:
                pass
        return self.object.get_absolute_url()

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            "object_url": self.get_object_url(),
        }


user_preview_view = UserPreviewView.as_view()


class UserStreamView(BaseUserActivityStreamView):

    template_name = "users/detail/activities.html"

    def get_ordering(self):
        if self.is_current_user:
            return "-created"
        return "-published"

    def filter_queryset(self, queryset):
        qs = (
            super()
            .filter_queryset(queryset)
            .exclude_blocked_tags(self.request.user)
            .filter(owner=self.user_obj)
        )
        if self.is_current_user:
            return qs.published_or_owner(self.request.user)
        return qs.published()

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            **{
                "num_likes": (
                    Like.objects.for_models(*get_activity_models())
                    .filter(recipient=self.user_obj, community=self.request.community)
                    .count()
                )
            },
        }


user_stream_view = UserStreamView.as_view()


class UserCommentListView(BaseUserCommentListView):
    template_name = "users/detail/comments.html"

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.user_obj).order_by("-created")

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            **{
                "num_likes": (
                    Like.objects.for_models(Comment)
                    .filter(recipient=self.user_obj, community=self.request.community)
                    .count()
                )
            },
        }


user_comment_list_view = UserCommentListView.as_view()


class UserMessageListView(SingleUserMixin, ListView):
    """
    Renders thread of all private messages between this user
    and the current user.
    """

    template_name = "users/detail/messages.html"
    paginate_by = settings.DEFAULT_PAGE_SIZE

    def get_queryset(self):
        if self.is_blocked:
            return Message.objects.none()
        qs = (
            Message.objects.for_community(self.request.community)
            .common_select_related()
            .order_by("-created")
            .distinct()
        )

        if self.is_current_user:
            qs = qs.for_sender_or_recipient(self.request.user)
        else:
            qs = qs.between(self.request.user, self.user_obj)
        return qs

    def get_num_messages_sent(self):
        return self.get_queryset().filter(sender=self.request.user).count()

    def get_num_messages_received(self):
        return self.get_queryset().filter(recipient=self.request.user).count()

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            **{
                "sent_messages": self.get_num_messages_sent(),
                "received_messages": self.get_num_messages_received(),
            },
        }


user_message_list_view = UserMessageListView.as_view()


class UserActivityLikesView(BaseUserActivityStreamView):
    """Liked activities published by this user."""

    template_name = "users/likes/activities.html"
    ordering = ("-num_likes", "-published")

    exclude_blocking_users = True

    def filter_queryset(self, queryset):
        return (
            super()
            .filter_queryset(queryset)
            .with_num_likes()
            .published()

templates/users/list/autocomplete.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load users %}

{% for user_obj in object_list %}
<li class="cursor-pointer p-1 hover:bg-gray-500 hover:text-white {% if forloop.first %} bg-gray-500 text-white selected{% endif %}"
    data-action="click->typeahead#select"
    data-typeahead-value="{{ user_obj.username }}"
    data-typeahead-key="@">
  <div class="flex items-center">
    <span class="inline-block">
      @{{ user_obj.username }}
    </span>
  </div>
</li>
{% endfor %}

templates/users/list/base.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "base.html" %}
{% load i18n %}
{% load rules %}

{% block subtitle %} / {% trans "People" %}{% endblock %}

{% block content %}

{% has_perm "private_messages.create_message" user community as can_create_message %}

<h1 class="page-header mb-3">{% trans "People" %}</h1>

<div class="tabs mb-3 text-sm">
  <a class="tab-item"
     data-controller="active-link"
     data-active-link-exact
     href="{% url 'users:member_list' %}">{% trans "Members" %}</a>
  <a class="tab-item"
     data-controller="active-link"
     data-active-link-exact
     href="{% url 'users:following_list' %}">{% trans "Following" %}</a>
  <a class="tab-item"
     data-controller="active-link"
     data-active-link-exact
     href="{% url 'users:follower_list' %}">{% trans "Followers" %}</a>
  <a class="tab-item"
     data-controller="active-link"
     data-active-link-exact
     href="{% url 'users:blocked_list' %}">{% trans "Blocked" %}</a>
</div>

{% block user_list %}

{% if object_list %}

{% block counter_container %}
<div class="notification font-bold mb-3">
  {% block counter %}
  {% endblock counter %}
</div>
{% endblock counter_container %}

{% if page_obj.number > 1 %}
{% include "includes/pagination.html" with css_class="mb-3" %}
{% endif %}

<table class="table-auto-scroll text-sm">
  <tbody>
    {% for object in object_list %}
    <tr class="{% cycle '' 'bg-gray-100' %} hover:bg-gray-200">
      <td class="border-t border-l border-b py-2 px-2 w-3/4">
        <div class="flex flex-wrap items-center">

          {% block user_item_detail %}
          {% if object.num_unread_messages %}
          {% url 'users:messages' object.username as messages_url %}
          {% include "users/includes/chip.html" with profile=object profile_url=messages_url css_class="mr-2" %}
          {% else %}
          {% include "users/includes/chip.html" with profile=object css_class="mr-2" %}
          {% endif %}

          {% if object.role == "admin" or object.role == "moderator" %}
          <span class="tag px-1 mr-2">{{ object.role_display }}</span>
          {% endif %}

          {% if object.num_unread_messages %}
          <span class="tag px-1">{% trans "New" %}</span>
          {% endif %}
          {% endblock user_item_detail %}
      </td>
      <td class="border py-2 px-2">
        <div class="table-nav">
          {% block user_item_actions %}
          {% if user == object %}
          <a class="table-nav-item"
             href="{% url 'user_update' %}">{% trans "Settings" %}</a>
          {% else %}
          {% has_perm "users.follow_user" user object as can_follow_user %}
          {% if can_follow_user %}

          <span data-controller="ajax"
                data-ajax-replace
                class="table-nav-item">
            {% include "users/includes/follow.html" with is_following=object.is_following %}
          </span>
          {% endif %}

          {% if can_create_message %}
          <a class="table-nav-item"
             href="{% url 'private_messages:message_create_recipient' object.username %}">
            {% trans "Send Message" %}
          </a>
          {% endif %}

          {% endif %}
        </div>
        {% endblock user_item_actions %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}
{% endblock user_list %}
{% endblock content %}

templates/users/list/blocked.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Blocked" %}{% endblock %}

{% block counter %}
{% blocktrans count counter=paginator.count %}
You have blocked one person.
{% plural %}
You have blocked {{ counter }} people.
{% endblocktrans %}
{% endblock counter %}

{% block user_item_actions %}
<div class="table-nav">
  <a class="table-nav-item line-through"
     href="{% url 'users:unblock' object.username %}"
     data-turbolinks="false"
     data-controller="ajax"
     data-action="ajax#post toggle#toggle"
     data-ajax-redirect="{{ request.get_full_path }}">
    {% trans "Block" %}
  </a>
</div>
{% endblock %}

templates/users/list/followers.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Followers" %}{% endblock %}

{% block counter %}
{% blocktrans count counter=paginator.count %}
You have one follower.
{% plural %}
You have {{ counter }} followers.
{% endblocktrans %}
{% endblock counter %}

templates/users/list/following.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Following" %}{% endblock %}

{% block counter %}
{% blocktrans count counter=paginator.count %}
You are following one person.
{% plural %}
You are following {{ counter }} people.
{% endblocktrans %}
{% endblock counter %}

templates/users/list/members.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Members" %}{% endblock %}

{% block counter_container %}
{% if not view.search_query %}
{{ block.super }}
{% endif %}
{% endblock counter_container %}


{% block counter %}
{% blocktrans count counter=paginator.count %}
This site has one member.
{% plural %}
This site has {{ counter }} members.
{% endblocktrans %}
{% endblock counter %}

{% block user_list %}
<div class="mb-1">
  {% include "includes/forms/search_form.html" with selector=True %}
</div>
{{ block.super }}
{% endblock user_list %}