localhub/bookmarks/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from .views import (
    bookmarks_comment_list_view,
    bookmarks_message_list_view,
    bookmarks_stream_view,
)

app_name = "bookmarks"

urlpatterns = [
    path("", bookmarks_stream_view, name="activities"),
    path("comments/", bookmarks_comment_list_view, name="comments"),
    path("messages/", bookmarks_message_list_view, name="messages"),
]

localhub/flags/urls.py
# Django
from django.urls import path

# Local
from .views import flag_delete_view, flag_list_view

app_name = "flags"


urlpatterns = [
    path("", view=flag_list_view, name="list"),
    path("<int:pk>/~delete/", view=flag_delete_view, name="delete"),
]

localhub/notifications/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from . import views

app_name = "notifications"

urlpatterns = [
    path("", views.notification_list_view, name="list"),
    path("service-worker.js", views.service_worker_view, name="service_worker"),
    path("~subscribe/", views.subscribe_view, name="subscribe"),
    path("~unsubscribe/", views.unsubscribe_view, name="unsubscribe"),
    path("<int:pk>/~delete/", views.notification_delete_view, name="delete"),
    path("<int:pk>/~mark-read/", views.notification_mark_read_view, name="mark_read"),
    path(
        "<int:pk>/~mark-read+redirect/",
        views.notification_mark_read_redirect_view,
        name="mark_read_redirect",
    ),
    path("~delete-all/", views.notification_delete_all_view, name="delete_all"),
    path(
        "~mark-all-read/", views.notification_mark_all_read_view, name="mark_all_read",
    ),
]

localhub/private_messages/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Localhub
from localhub.users.urls import user_re_path

# Local
from . import views

app_name = "private_messages"

urlpatterns = [
    path("inbox/", views.inbox_view, name="inbox"),
    path("outbox/", views.outbox_view, name="outbox"),
    path("send/", views.message_create_view, name="message_create"),
    path("~/mark-read/", views.message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", views.message_detail_view, name="message_detail"),
    path(
        "message/<int:pk>/~follow-up/",
        views.message_follow_up_view,
        name="message_follow_up",
    ),
    path("message/<int:pk>/~reply/", views.message_reply_view, name="message_reply"),
    path("message/<int:pk>/~delete/", views.message_delete_view, name="message_delete"),
    path(
        "message/<int:pk>/~read/",
        views.message_mark_read_view,
        name="message_mark_read",
    ),
    path(
        "message/<int:pk>/~bookmark/",
        views.message_bookmark_view,
        name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        views.message_remove_bookmark_view,
        name="message_remove_bookmark",
    ),
    user_re_path(
        r"~send/$",
        views.message_recipient_create_view,
        name="message_create_recipient",
    ),
]

localhub/bookmarks/models.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

# Third Party Libraries
from model_utils.models import TimeStampedModel

# Localhub
from localhub.communities.models import Community
from localhub.db.generic import (
    get_generic_related_exists,
    get_generic_related_value_subquery,
)
from localhub.db.utils import boolean_value


class BookmarkAnnotationsQuerySetMixin:
    """
    Annotation methods for related model query sets.
    """

    def exists_bookmarks(self, user):
        return get_generic_related_exists(
            self.model, Bookmark.objects.filter(user=user)
        )

    def with_has_bookmarked(self, user, annotated_name="has_bookmarked"):
        """Checks if user has liked the objects, adding `has_liked`
        annotation.

        Args:

            user (User): user who has bookmarked the items
            annotated_name (str, optional): annotation name (default: "has_bookmarked")

        Returns:

            QuerySet
        """
        return self.annotate(
            **{
                annotated_name: boolean_value(False)
                if user.is_anonymous
                else self.exists_bookmarks(user)
            }
        )

    def bookmarked(self, user, annotated_name="has_bookmarked"):
        """Filters queryset and returns only those which have been bookmarked.

        Args:

            user (User): user who has bookmarked the items
            annotated_name (str, optional): annotation name (default: "has_bookmarked")

        Returns:

            QuerySet
        """
        if user.is_anonymous:
            return self.none()

        return self.filter(self.exists_bookmarks(user)).annotate(
            **{annotated_name: boolean_value(True)}
        )

    def with_bookmarked_timestamp(self, user, annotated_name="bookmarked"):
        """Adds annotated "bookmarked" timestamp to bookmarked items.

        Args:
            user (User): user who has bookmarked the items
            annotated_name (str, optional): annotation timestamp name (default: "bookmarked")

        Returns:
            QuerySet
        """

        if user.is_anonymous:
            return self.none()

        return self.annotate(
            **{
                annotated_name: get_generic_related_value_subquery(
                    self.model,
                    Bookmark.objects.filter(user=user),
                    "created",
                    models.DateTimeField(),
                )
            }
        )


class BookmarkQuerySet(models.QuerySet):
    def for_models(self, *models):
        """
        Returns instances of a Bookmark for a given set of models.
        """
        return self.filter(
            content_type__in=ContentType.objects.get_for_models(*models).values()
        )


class Bookmark(TimeStampedModel):

    community = models.ForeignKey(Community, related_name="+", on_delete=models.CASCADE)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="+", on_delete=models.CASCADE
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    objects = BookmarkQuerySet.as_manager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "content_type", "object_id"], name="unique_bookmark",
            )
        ]
        indexes = [models.Index(fields=["content_type", "object_id"])]

localhub/private_messages/forms.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


# Django
from django import forms
from django.core.exceptions import ImproperlyConfigured, ValidationError
from django.utils.translation import gettext_lazy as _

# Localhub
from localhub.users.forms import MentionsField
from localhub.users.utils import extract_mentions

# Local
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("message",)


class MessageRecipientForm(MessageForm):
    """Adds an extra recipient field to allow sender to lookup
    a recipient for this message.
    """

    recipient = MentionsField(
        required=True, help_text=_("Use @mention format to find and add a recipient"),
    )

    class Meta(MessageForm.Meta):
        fields = (
            "recipient",
            "message",
        )

    def __init__(self, *args, **kwargs):
        self.community = kwargs.pop("community", None)
        self.sender = kwargs.pop("sender", None)
        super().__init__(*args, **kwargs)

    def clean_recipient(self):
        if self.community is None:
            raise ImproperlyConfigured(
                "community must be provided if recipient field is used"
            )
        if self.sender is None:
            raise ImproperlyConfigured(
                "sender must be provided if recipient field is used"
            )
        # validate that all mentioned recipients are community members
        usernames = extract_mentions(self.cleaned_data["recipient"])
        if len(usernames) > 1:
            raise ValidationError(_("You can only select one recipient at a time"))
        recipient = (
            self.community.get_members()
            .matches_usernames(usernames)
            .exclude_blocking(self.sender)
            .exclude(pk=self.sender.pk)
            .first()
        )
        if recipient is None:
            raise ValidationError(_("No active member found matching this name"))
        return recipient

localhub/bookmarks/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Localhub
from localhub.activities.views.streams import BaseActivityStreamView
from localhub.comments.views import BaseCommentListView
from localhub.private_messages.views import (
    BaseMessageListView,
    SenderOrRecipientQuerySetMixin,
)
from localhub.views import SearchMixin


class BookmarksStreamView(SearchMixin, BaseActivityStreamView):
    template_name = "bookmarks/activities.html"
    ordering = ("-bookmarked", "-created")

    def filter_queryset(self, queryset):
        qs = (
            super()
            .filter_queryset(queryset)
            .published_or_owner(self.request.user)
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
        )
        if self.search_query:
            qs = qs.search(self.search_query)
        return qs


bookmarks_stream_view = BookmarksStreamView.as_view()


class BookmarksMessageListView(SenderOrRecipientQuerySetMixin, BaseMessageListView):
    template_name = "bookmarks/messages.html"

    def get_queryset(self):
        qs = (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )
        if self.search_query:
            qs = qs.search(self.search_query)
        return qs


bookmarks_message_list_view = BookmarksMessageListView.as_view()


class BookmarksCommentListView(SearchMixin, BaseCommentListView):
    template_name = "bookmarks/comments.html"

    def get_queryset(self):
        qs = (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_common_annotations(self.request.user, self.request.community)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )
        if self.search_query:
            qs = qs.search(self.search_query)
        return qs


bookmarks_comment_list_view = BookmarksCommentListView.as_view()

localhub/notifications/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Standard Library
import json

# Django
from django.conf import settings
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, View

# Localhub
from localhub.communities.views import CommunityRequiredMixin
from localhub.views import SuccessActionView, SuccessDeleteView, SuccessView

# Local
from .models import Notification, PushSubscription
from .signals import notification_read


class NotificationQuerySetMixin(CommunityRequiredMixin):
    def get_queryset(self):
        return Notification.objects.for_community(self.request.community).for_recipient(
            self.request.user
        )


class UnreadNotificationQuerySetMixin(NotificationQuerySetMixin):
    def get_queryset(self):
        return super().get_queryset().unread()


class NotificationSuccessRedirectMixin:
    success_url = reverse_lazy("notifications:list")


class NotificationListView(NotificationQuerySetMixin, ListView):
    paginate_by = settings.LONG_PAGE_SIZE
    template_name = "notifications/notification_list.html"
    model = Notification

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .exclude_blocked_actors(self.request.user)
            .prefetch_related("content_object")
            .select_related("actor", "content_type", "community", "recipient")
            .order_by("is_read", "-created")
        )

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data.update(
            {
                "is_unread_notifications": self.get_queryset()
                .filter(is_read=False)
                .exists(),
                "webpush_settings": {
                    "public_key": settings.VAPID_PUBLIC_KEY,
                    "enabled": settings.WEBPUSH_ENABLED,
                },
            }
        )
        return data


notification_list_view = NotificationListView.as_view()


class NotificationMarkAllReadView(
    UnreadNotificationQuerySetMixin, NotificationSuccessRedirectMixin, SuccessView,
):
    def post(self, request, *args, **kwargs):
        qs = self.get_queryset()
        [
            notification_read.send(
                sender=notification.content_object.__class__,
                instance=notification.content_object,
            )
            for notification in qs.prefetch_related("content_object")
        ]
        qs.update(is_read=True)
        return self.success_response()


notification_mark_all_read_view = NotificationMarkAllReadView.as_view()


class NotificationMarkReadView(UnreadNotificationQuerySetMixin, SuccessActionView):
    is_success_ajax_response = True

    def post(self, request, *args, **kwargs):
        self.object.is_read = True
        self.object.save()

        notification_read.send(
            sender=self.object.content_object.__class__,
            instance=self.object.content_object,
        )
        return self.success_response()


notification_mark_read_view = NotificationMarkReadView.as_view()


class NotificationMarkReadRedirectView(
    NotificationSuccessRedirectMixin, NotificationMarkReadView
):
    is_success_ajax_response = False


notification_mark_read_redirect_view = NotificationMarkReadRedirectView.as_view()


class NotificationDeleteAllView(
    NotificationQuerySetMixin, NotificationSuccessRedirectMixin, SuccessView
):
    def delete(self, request):
        self.get_queryset().delete()
        return HttpResponseRedirect(self.get_success_url())

    def post(self, request):
        return self.delete(request)


notification_delete_all_view = NotificationDeleteAllView.as_view()


class NotificationDeleteView(
    NotificationQuerySetMixin, NotificationSuccessRedirectMixin, SuccessDeleteView
):

    ...


notification_delete_view = NotificationDeleteView.as_view()


class BasePushSubscriptionView(CommunityRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            json_body = json.loads(request.body.decode("utf-8"))

            data = {"endpoint": json_body["endpoint"]}
            keys = json_body["keys"]
            data["auth"] = keys["auth"]
            data["p256dh"] = keys["p256dh"]

        except (ValueError, KeyError):
            return HttpResponseBadRequest()

        return self.handle_action(request, **data)

    def handle_action(self, request, auth, p256dh, endpoint):
        raise NotImplementedError


class ServiceWorkerView(TemplateView):
    """
    Returns template containing serviceWorker JS, can't use
    static as must always be under domain. We can also pass
    in server specific settings.
    """

    template_name = "notifications/service_worker.js"

    def get(self, request):
        response = super().get(request)
        response["Content-Type"] = "application/javascript"
        return response

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["vapid_public_key"] = settings.VAPID_PUBLIC_KEY
        return data


service_worker_view = ServiceWorkerView.as_view()


class SubscribeView(BasePushSubscriptionView):
    def handle_action(self, request, auth, p256dh, endpoint):

        try:
            PushSubscription.objects.get_or_create(
                auth=auth,
                p256dh=p256dh,
                endpoint=endpoint,
                user=request.user,
                community=request.community,
            )
        except IntegrityError:
            pass  # dupe, ignore

        return JsonResponse({"message": "ok"}, status=201)


subscribe_view = SubscribeView.as_view()


class UnsubscribeView(BasePushSubscriptionView):
    def handle_action(self, request, auth, p256dh, endpoint):

        PushSubscription.objects.filter(
            auth=auth,
            p256dh=p256dh,
            endpoint=endpoint,
            user=request.user,
            community=request.community,
        ).delete()

        return JsonResponse({"message": "ok"}, status=200)


unsubscribe_view = UnsubscribeView.as_view()

templates/private_messages/includes/bookmark.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if has_bookmarked %}
<a href="{% url 'private_messages:message_remove_bookmark' object.id %}"
   class="dropdown-menu-item line-through"
   data-turbolinks="false"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Bookmark" %}</a>
{% else %}
<a href="{% url 'private_messages:message_bookmark' object.id %}"
   class="dropdown-menu-item"
   data-turbolinks="false"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Bookmark" %}</a>
{% endif %}

templates/private_messages/includes/email_settings.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load users %}

{% dismissable user "messages-emails" %}
{% url 'user_update' as user_settings_url %}
{% blocktrans %}
You can enable email notifications for new messages <a href="{{ user_settings_url }}">in your settings</a>.
{% endblocktrans %}
{% enddismissable %}

templates/private_messages/includes/message.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load account %}
{% load users %}

<div class="card {{ css_class|default:"mb-3" }}"
     id="message-{{ message.id }}"
     data-controller="clipboard"
     data-clipboard-message="{% trans 'Markdown content has been copied' %}">

  <div class="flex flex-wrap items-center mb-3">
    {% include "users/includes/chip.html" with profile=message.sender profile_url=sender_url css_class="mr-2" %}
    <div class="mr-2 text-muted text-sm">
      {% trans "to" %}
    </div>
    {% include "users/includes/chip.html" with profile=message.recipient profile_url=recipient_url css_class="mr-2" %}
    <span class="mr-2 text-muted text-sm">
      {% blocktrans with created=message.created|timesince %}
      {{ created }} ago
      {% endblocktrans %}
    </span>
    {% if is_unread %}
    <div class="tag tag-primary">{% trans "New" %}</div>
    {% endif %}
  </div>

  {% collapsable is_detail %}
  <div class="markdown-content mb-3">
    {{ message.message.markdown|strip_external_images:user|lazify }}
  </div>
  {% endcollapsable %}
  <textarea data-target="clipboard.textarea"
            readonly
            class="hidden">{{ message.message }}</textarea>

  <div class="card-footer">
    <div class="flex flex-wrap items-center">
      <div class="mr-2 text-sm"
           data-controller="dropdown"
           data-action="click@window->dropdown#close keydown@window->dropdown#close">
        <button class="btn btn-dropdown"
                data-action="dropdown#toggle">
          {% trans "Actions..." %}
        </button>

        <div class="dropdown-menu hidden mt-1"
             data-target="dropdown.menu">

          {% if is_recipient and not message.read %}
          <a href="{% url 'private_messages:message_mark_read' message.id %}"
             class="dropdown-menu-item"
             data-turbolinks="false"
             data-controller="ajax"
             data-action="ajax#post"
             data-ajax-redirect="{{ request.get_full_path }}">{% trans "Mark As Read" %}</a>
          {% endif %}

          <div class="menu-item"
               data-controller="ajax"
               data-ajax-replace>
            {% include "private_messages/includes/bookmark.html" with object=message has_bookmarked=message.has_bookmarked %}
          </div>

          {% if can_reply %}
          <a href="{% url 'private_messages:message_reply' message.id %}"
             class="dropdown-menu-item">
            {% trans "Reply" %}
          </a>
          {% elif can_follow_up %}
          <a href="{% url 'private_messages:message_follow_up' message.id %}"
             class="dropdown-menu-item">
            {% trans "Follow-Up" %}
          </a>
          {% endif %}
          <a href="{% url 'private_messages:message_delete' message.id %}"
             class="dropdown-menu-item"
             data-turbolinks="false"
             data-controller="ajax"
             data-action="ajax#post"
             data-ajax-redirect="{{ post_delete_redirect|default:request.get_full_path }}"
             data-ajax-confirm-header="{% trans 'Delete Message' %}"
             data-ajax-confirm-body="{% trans "Are you sure you want to delete this message? Replies to this message will not be deleted. The message may still be available to the other person." %}">{% trans "Delete" %}</a>

          <a href="#"
             class="dropdown-menu-item"
             data-turbolinks="false"
             data-target="clipboard.button"
             data-action="clipboard#copy">
            {% trans "Copy Markdown" %}
          </a>
        </div>

      </div>
      {% if not is_detail %}
      <a class="inline-block mr-2 text-sm"
         href="{{ message_url }}">{% trans "Link" %}</a>
      {% if parent %}
      <a class="inline-block text-sm"
         href="{{ parent_url }}">{% trans "Parent" %}</a>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>

templates/private_messages/includes/message_list.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load private_messages %}

{% if page_obj.number > 1 %}
{% include "includes/pagination.html" with css_class="mb-3" %}
{% endif %}

{% if object_list %}
{% for message in object_list %}
{% render_message request user message %}
{% endfor %}
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}

templates/private_messages/includes/notification.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if verb == "reply" %}
{% blocktrans %}
<a href="{{ actor_url }}"
   data-controller="hovercard"
   data-hovercard-url="{{ actor_preview_url }}"
   data-action="mouseenter->hovercard#show mouseleave->hovercard#hide">
  {{ actor_display }}</a> has replied to your <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% elif verb == "follow_up" %}
{% blocktrans %}
<a href="{{ actor_url }}"
   data-controller="hovercard"
   data-hovercard-url="{{ actor_preview_url }}"
   data-action="mouseenter->hovercard#show mouseleave->hovercard#hide">
  {{ actor_display }}</a> has sent you a <a href="{{ object_url }}">follow-up</a> to one of
their messages.
{% endblocktrans %}
{% else %}
{% blocktrans %}
<a href="{{ actor_url }}"
   data-controller="hovercard"
   data-hovercard-url="{{ actor_preview_url }}"
   data-action="mouseenter->hovercard#show mouseleave->hovercard#hide">
  {{ actor_display }}</a> has sent you a <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% endif %}