localhub/activities/events/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


# Django
from django.urls import path

# Localhub
from localhub.activities.urls.generic import create_activity_urls

# Local
from . import views
from .forms import EventForm
from .models import Event

app_name = "events"


urlpatterns = create_activity_urls(
    Event,
    EventForm,
    create_view_class=views.EventCreateView,
    list_view_class=views.EventListView,
)

urlpatterns += [
    path("calendar/", views.event_calendar_view, name="calendar"),
    path("<int:pk>~attend/", views.event_attend_view, name="attend"),
    path("<int:pk>~unattend/", views.event_unattend_view, name="unattend"),
    path("<int:pk>~cancel/", views.event_cancel_view, name="cancel"),
    path("<int:pk>~download/", views.event_download_view, name="download"),
]

localhub/flags/urls.py
# Django
from django.urls import path

# Local
from .views import flag_delete_view, flag_list_view

app_name = "flags"


urlpatterns = [
    path("", view=flag_list_view, name="list"),
    path("<int:pk>/~delete/", view=flag_delete_view, name="delete"),
]

localhub/invites/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from . import views

app_name = "invites"


urlpatterns = [
    path("", views.invite_list_view, name="list"),
    path("received/", views.received_invite_list_view, name="received_list"),
    path("~create/", views.invite_create_view, name="create"),
    path("<pk>/~resend/", views.invite_resend_view, name="resend"),
    path("<pk>/~delete/", views.invite_delete_view, name="delete"),
    path("<pk>/~accept/", views.invite_accept_view, name="accept"),
    path("<pk>/~reject/", views.invite_reject_view, name="reject"),
    path("<pk>/", views.invite_detail_view, name="detail"),
]

localhub/activities/events/forms.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django import forms
from django.utils.timezone import localtime, make_aware
from django.utils.translation import gettext_lazy as _

# Third Party Libraries
import pytz

# Localhub
from localhub.activities.forms import ActivityForm
from localhub.forms import CalendarField, CalendarWidget, FormHelper
from localhub.utils.geocode import geocode

# Local
from .models import Event

DATE_FORMATS = ["%d/%m/%Y"]


class EventForm(ActivityForm):

    starts = CalendarField(
        label=_("Event starts"),
        input_date_formats=DATE_FORMATS,
        widget=CalendarWidget(notify="event:starts", default_time="09:00"),
    )

    ends = CalendarField(
        label=_("Event ends"),
        required=False,
        input_date_formats=DATE_FORMATS,
        widget=CalendarWidget(listen="event:starts", default_time="09:00"),
        help_text=_("Leave empty if it's an all-day event"),
    )

    repeats_until = CalendarField(
        label=_("Repeat until"),
        input_date_formats=DATE_FORMATS,
        required=False,
        widget=CalendarWidget(listen="event:starts", default_time="09:00"),
    )

    clear_geolocation = forms.BooleanField(
        label=_("Remove event from map"), required=False
    )

    fetch_geolocation = forms.BooleanField(
        label=_("Add event to map if address provided"), required=False
    )

    class Meta(ActivityForm.Meta):
        model = Event
        fields = (
            "title",
            "hashtags",
            "mentions",
            "starts",
            "ends",
            "repeats",
            "repeats_until",
            "timezone",
            "url",
            "description",
            "allow_comments",
            "venue",
            "street_address",
            "locality",
            "postal_code",
            "region",
            "country",
            "clear_geolocation",
            "fetch_geolocation",
            "latitude",
            "longitude",
        )
        localized_fields = ("starts", "ends")

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fieldsets = FormHelper(
            self,
            (
                None,
                (
                    "title",
                    "hashtags",
                    "mentions",
                    "starts",
                    "ends",
                    "repeats",
                    "repeats_until",
                    "timezone",
                    "url",
                    "description",
                    "allow_comments",
                ),
            ),
            (
                _("Location"),
                (
                    "venue",
                    "street_address",
                    "locality",
                    "postal_code",
                    "region",
                    "country",
                    "clear_geolocation",
                    "fetch_geolocation",
                ),
            ),
        )
        self.fields["latitude"].widget = forms.HiddenInput()
        self.fields["longitude"].widget = forms.HiddenInput()

        self.fields["repeats"].help_text = _("Will repeat from the start date onwards")

        self.fields["timezone"].help_text = _(
            "Start and end times will be shown in this timezone"
        )

        # convert the UTC stored value into the local time the user
        # originally entered according to their timezone. The final value
        # must be UTC, otherwise the field will just convert it again
        # to the database value.

        for field in ("starts", "ends"):
            value = getattr(self.instance, field)
            if value:
                self.initial[field] = make_aware(
                    localtime(value, self.instance.timezone).replace(tzinfo=None),
                    pytz.UTC,
                    is_dst=True,
                )

        if self.instance.has_map():
            self.fields["fetch_geolocation"].label = _("Recalculate position on map")
        else:
            del self.fields["clear_geolocation"]

    def clean(self):
        cleaned_data = super().clean()
        timezone = cleaned_data["timezone"]

        # We don't want to do a timezone conversion, just preserve
        # the user entered value. Make a naive datetime stripping out UTC
        # and just set the timezone. Then do a timezone conversion
        # back to UTC to get the actual UTC value we want to store in the
        # database.

        # for example, if the user enters starts value 09:00 and timezone
        # Helsinki, we store the value in the database as 06:00 UTC.

        for field in ("starts", "ends"):
            value = cleaned_data.get(field)
            if value:
                cleaned_data[field] = localtime(
                    make_aware(value.replace(tzinfo=None), timezone, is_dst=True),
                    pytz.UTC,
                )

        if cleaned_data.get("clear_geolocation"):
            cleaned_data["latitude"], cleaned_data["longitude"] = None, None

        elif cleaned_data["fetch_geolocation"]:
            latitude, longitude = geocode(
                cleaned_data["street_address"],
                cleaned_data["locality"],
                cleaned_data["postal_code"],
                cleaned_data["country"],
            )
            if None in (latitude, longitude):
                raise forms.ValidationError(_("Unable to locate address on map"))
            cleaned_data["latitude"] = latitude
            cleaned_data["longitude"] = longitude

        return cleaned_data

localhub/activities/events/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Standard Library
import calendar
import datetime

# Django
from django.http import Http404, HttpResponse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django.views.generic import View
from django.views.generic.dates import DateMixin, DayMixin, MonthMixin, YearMixin
from django.views.generic.detail import SingleObjectMixin

# Third Party Libraries
import pytz

# Localhub
from localhub.activities.views.generic import (
    ActivityCreateView,
    ActivityListView,
    ActivityQuerySetMixin,
    BaseActivityActionView,
    BaseActivityListView,
)

# Local
from .models import Event


class TimezoneOverrideMixin:
    def dispatch(self, request, *args, **kwargs):
        with timezone.override(
            request.user.default_timezone if request.user.is_authenticated else None
        ):
            return super().dispatch(request, *args, **kwargs)


class BaseEventActionView(BaseActivityActionView):

    model = Event


class EventCancelView(BaseEventActionView):
    success_message = _("This event has been canceled")

    permission_required = "events.cancel"

    def post(self, request, *args, **kwargs):
        self.object.canceled = timezone.now()
        self.object.save()
        self.object.notify_on_cancel(self.request.user)
        return self.success_response()


event_cancel_view = EventCancelView.as_view()


class BaseEventAttendView(BaseEventActionView):
    permission_required = "events.attend"
    is_success_ajax_response = True
    success_template_name = "events/includes/attend.html"


class EventAttendView(BaseEventAttendView):
    success_message = _("You are now attending this event")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.attendees.add(self.request.user)
        self.object.notify_on_attend(self.request.user)
        return self.success_response()

    def get_success_context_data(self):
        return {**super().get_success_context_data(), "is_attending": True}


event_attend_view = EventAttendView.as_view()


class EventUnattendView(BaseEventAttendView):
    success_message = _("You are no longer attending this event")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.attendees.remove(self.request.user)
        return self.success_response()

    def get_success_context_data(self):
        return {**super().get_success_context_data(), "is_attending": False}


event_unattend_view = EventUnattendView.as_view()


class EventDownloadView(
    ActivityQuerySetMixin, SingleObjectMixin, TimezoneOverrideMixin, View
):
    """
    Generates a calendar .ics file.
    """

    model = Event

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        response = HttpResponse(content_type="text/calendar")
        response.write(self.object.to_ical())
        return response


event_download_view = EventDownloadView.as_view()


class EventCreateView(TimezoneOverrideMixin, ActivityCreateView):
    def get_initial(self):
        initial = super().get_initial()
        initial["timezone"] = self.request.user.default_timezone
        initial["starts"] = self.get_start_date()
        return initial

    def get_start_date(self):
        try:
            [day, month, year] = [
                int(self.request.GET[param]) for param in ("day", "month", "year")
            ]
            return datetime.datetime(day=day, month=month, year=year, hour=9)
        except (KeyError, ValueError):
            return None


class EventListView(TimezoneOverrideMixin, ActivityListView):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_relevance()
            .with_timedelta()
            .order_by("-relevance", "timedelta")
        )


class EventCalendarView(
    YearMixin,
    MonthMixin,
    DayMixin,
    DateMixin,
    TimezoneOverrideMixin,
    BaseActivityListView,
):
    template_name = "events/calendar.html"
    date_field = "starts"
    paginate_by = None
    allow_future = True
    model = Event

    def get_allow_empty(self):
        # empty month view is fine, but you should not be able
        # to navigate to a single date missing any events.
        return not (self.current_day)

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Event.InvalidDate:
            raise Http404("These dates are not valid")

    def get_current_time(self):
        return timezone.localtime(timezone.now())

    @cached_property
    def current_day(self):
        try:
            return int(self.get_day())
        except (Http404, ValueError):
            return None

    @cached_property
    def current_month(self):
        try:
            return int(self.get_month())
        except (Http404, ValueError):
            return self.get_current_time().month

    @cached_property
    def current_year(self):
        try:
            return int(self.get_year())
        except (Http404, ValueError):
            return self.get_current_time().year

    def get_queryset(self):
        # for rep
        qs = (
            super()
            .get_queryset()
            .published_or_owner(self.request.user)
            .with_next_date()
            .exclude_blocked(self.request.user)
            .filter(parent__isnull=True)
            .order_by("next_date")
        )
        if self.current_day:
            qs = qs.for_date(
                self.current_day, self.current_month, self.current_year
            ).with_common_annotations(self.request.user, self.request.community)
        else:
            qs = qs.for_month(self.current_month, self.current_year)
        return qs

    def make_date(self, day):
        return self.make_datetime(day).date()

    def make_datetime(self, day):
        try:
            return timezone.localtime(
                datetime.datetime(
                    day=day,
                    month=self.current_month,
                    year=self.current_year,
                    tzinfo=pytz.UTC,
                )
            )
        except ValueError:
            raise Event.InvalidDate()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        if self.current_day:
            data["current_date"] = self.make_date(self.current_day)
            match_datetime = self.make_datetime(self.current_day)
            data["events"] = [
                event
                for event in self.object_list
                if event.matches_date(match_datetime)
            ]
            return data

        now = self.get_current_time()

        data["current_month"] = first_of_month = self.make_date(1)

        return {
            **data,
            **{
                "next_month": self.get_next_month(first_of_month),
                "previous_month": self.get_previous_month(first_of_month),
                "slots": self.get_slots(),
                "today": now,
                "is_current_month": now.month == first_of_month.month
                and now.year == first_of_month.year,
            },
        }

    def get_slots(self):
        """Group events by day into tuples of (number, events)"""

        return [
            (
                day,
                is_past,
                [event for event in self.object_list if dt and event.matches_date(dt)],
            )
            for day, is_past, dt in self.iter_dates()
        ]

    def is_past(self, day):
        now = timezone.now()
        # any month in the future
        if self.current_month > now.month and self.current_year >= now.year:
            return False

        # any month in the past
        if self.current_month < now.month:
            return True

        # this month
        return now.day > day

    def iter_dates(self):
        """Yields tuple of (counter, is_past, datetime) for each day of month. If day
        falls out of range yields zero, False, None.
        """
        try:
            for day in calendar.Calendar().itermonthdays(
                self.current_year, self.current_month
            ):
                if day > 0:
                    yield day, self.is_past(day), self.make_datetime(day=day)
                else:
                    # falls outside the day range
                    yield 0, False, None
        except ValueError:
            raise Event.InvalidDate()


event_calendar_view = EventCalendarView.as_view()

templates/events/includes/actions.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/actions.html" %}

{% load i18n %}
{% load rules %}

{% block extra_actions %}

{% has_perm "events.attend" user object as can_attend %}

{% if can_attend %}
<div data-controller="ajax" data-ajax-replace>
  {% include "events/includes/attend.html" with is_attending=object.is_attending %}
</div>
{% endif %}

{% if object.is_attendable %}
<a href="{% url 'events:download' object.id %}"
   class="dropdown-menu-item"
   data-turbolinks="false"
   download>
  {% trans 'Download' %}
</a>
{% endif %}

{% has_perm "events.cancel" user object as can_cancel %}
{% if can_cancel %}
<a href="{% url 'events:cancel' object.id %}"
   class="dropdown-menu-item"
   data-controller="ajax"
   data-action="ajax#post"
   {% if not is_detail %}
   data-ajax-redirect="{{ request.get_full_path }}"
   {% endif %}
   data-ajax-confirm-header="{% trans 'Cancel' %}"
   data-ajax-confirm-body="{% trans 'Are you sure you want to cancel this event?' %}">
  {% trans "Cancel Event" %}</a>
{% endif %}


{% endblock %}

templates/events/includes/attend.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}


{% load i18n %}
{% if is_attending %}
<a href="{% url 'events:unattend' object.id %}"
   data-turbolinks="false"
   class="dropdown-menu-item line-through"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Attending" %}</a>
{% else %}
<a href="{% url 'events:attend' object.id %}"
   data-turbolinks="false"
   class="dropdown-menu-item"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Attending" %}</a>
{% endif %}

templates/events/includes/calendar.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
<div class="border-gray-500 min-w-100">
  <div class="flex items-center justify-between bg-indigo-900 text-white px-4 py-2 font-semibold border-r border-l border-t border-gray-500">
    <a class="text-sm text-white hover:text-gray-200"
       href="{{ request.path }}?month={{ previous_month.month }}&year={{ previous_month.year }}">
      {% trans "Previous" %}
    </a>
    <div class="font-semibold">{{ current_month|date:"F Y" }}</div>
    <a class="text-sm text-white hover:text-gray-200"
       href="{{ request.path }}?month={{ next_month.month }}&year={{ next_month.year }}">
      {% trans "Next" %}
    </a>
  </div>
  <div class="flex flex-wrap justify-between text-center items-center py-4 px-0 bg-blue-600 text-white font-semibold border-r border-l border-gray-500">
    <div class="text-sm calendar-item">{% trans "Mon" %}</div>
    <div class="text-sm calendar-item">{% trans "Tue" %}</div>
    <div class="text-sm calendar-item">{% trans "Wed" %}</div>
    <div class="text-sm calendar-item">{% trans "Thu" %}</div>
    <div class="text-sm calendar-item">{% trans "Fri" %}</div>
    <div class="text-sm calendar-item">{% trans "Sat" %}</div>
    <div class="text-sm calendar-item">{% trans "Sun" %}</div>
  </div>
  <div class="flex flex-wrap border-l border-gray-500">
    {% for day, is_past, events in slots %}
    {% with num_events=events|length %}
    <div class="calendar-item text-xs{% if not day %} bg-gray-200{% elif day == today.day and is_current_month %} bg-blue-600 {% if num_events %}hover:bg-blue-500{% endif %} text-white{% elif num_events %} bg-indigo-900 text-white hover:bg-indigo-700{% endif %}{% if num_events %} cursor-pointer{% endif %}"
         {% if num_events %}
         data-controller="linkify"
         data-action="click->linkify#fetch"
         data-linkify-url="{% if num_events == 1 %}{{ events.0.get_absolute_url }}{% else %}{{ request.path }}?day={{ day }}&month={{ current_month.month }}&year={{ current_month.year }}{% endif %}"
         {% endif %}>
      {% if day %}
      {% comment %}
      {% elif can_create_activity %}
      {% endcomment %}
      {% if can_create_activity and not events %}
      <div class="h-10 lg:h-32 p-2 border-b border-r border-gray-500 cursor-pointer"
           data-controller="linkify"
           data-action="click->linkify#fetch"
           data-linkify-url="{% url 'events:create' %}?day={{ day }}&month={{ current_month.month }}&year={{ current_month.year }}">
        {% else %}
        <div class="h-10 lg:h-32 p-2 tracking-tight border-r border-b border-gray-500 align-middle">
          {% endif %}
          <button>
            {{ day }}
            <span class="lg:hidden ml-1">
              {% for event in events|slice:5 %}&middot;{% endfor %}
            </span>
          </button>
          <div class="clear-both"></div>
          {% if events %}
          <div class="hidden lg:block text-xs{% if is_past %} text-gray-500{% endif %}">
            {% for event in events|slice:":2" %}

            <div class="{% if not event.is_attendable %} line-through{% elif event.is_attending %} font-semibold{% endif %}">{{ event.title }}</div>

            {% endfor %}

            {% if num_events > 2 %}
            <div href="#">{{ num_events|add:"-2" }} {% trans "More..." %}
            </div>
            {% endif %}

          </div>
          {% endif %}
        </div>
        {% else %}
        <div class="h-10 lg:h-32 p-2 border-b border-r border-gray-500"></div>
        {% endif %}
      </div>
      {% endwith %}
      {% endfor %}
    </div>
  </div>

templates/events/includes/event.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/activity_base.html" %}

{% load i18n %}

{% load tz %}
{% load activities %}

{% block content %}
{% with starts=object.get_next_start_date ends=object.get_next_end_date %}
{% if object.canceled %}
<p class="text-bold text-center py-2">{% trans "This event has been canceled." %}</p>
<div class="text-gray-600">
  {% endif %}

  <dl class="text-sm">

    {% timezone object.timezone %}
    {% if ends %}

    {% with start_date=starts|date:"SHORT_DATE_FORMAT" end_date=ends|date:"SHORT_DATE_FORMAT" start_time=starts|date:"TIME_FORMAT" end_time=ends|date:"TIME_FORMAT" %}

    {% if start_date == end_date %}

    <dt>
      {% trans "Date" %} <span class="tag">{{ object.timezone }}</span>
    </dt>

    <dd{% if not object.is_attendable %} class="line-through"
                                         {% endif %}>
      {{ starts|date:"D" }} {{ start_date }} @ {{ start_time }} - {{ end_time }}
      </dd>

      {% else %}
      <dt>{% trans "Dates" %} <span class="tag">{{ object.timezone }}</span></dt>

      <dd{% if not object.is_attendable %} class="line-through"
                                           {% endif %}>
      {{ starts|date:"D" }} {{ start_date }} @ {{ start_time }} - {{ ends|date:"D" }} {{ end_date }} @ {{ end_time }}</dd{%>
    {% endif %} {% endwith %}
                              {% else %}
                              <dt>{% trans "Date" %} <span class="tag">{{ object.timezone }}</span></dt>
      <dd{% if not object.is_attendable %} class="line-through"
                                           {% endif %}>
      {{ starts|date:"D" }} {{ starts|date:"SHORT_DATE_FORMAT" }} @ {{ starts|date:"TIME_FORMAT" }}
      </dd{%>

   {% endif %} {% if object.repeats %}
                              <dt>{% trans "Repeats" %}</dt>
      <dd>
        {% if object.repeats_weekly %}
        {% blocktrans with weekday=object.starts|date:"l" %}
        Same time every {{ weekday }}
        {% endblocktrans %}
        {% else %}
        {{ object.get_repeats_display }}
        {% endif %}
        {% if object.repeats_until %}
        {% blocktrans with until=object.repeats_until|date:"SHORT_DATE_FORMAT" %}
        until {{ until }}
        {% endblocktrans %}
        {% endif %}
      </dd>
      {% endif %}

      {% endtimezone %}
      {% with location=object.get_full_location %}
      {% if location %}
      <dt>{% trans "Location" %}</dt>
      <dd>
        {% if not is_detail and object.has_map %}
        <a href="{{ object.get_absolute_url }}#map-for-event-{{ object.id }}">{{ location }}</a>
        {% else %}
        {{ location }}
        {% endif %}
      </dd>
      {% endif %}
      {% endwith %}

      {% if object.url %}
      <dt>{% trans "URL" %}</dt>
      <dd class="truncate">{{ object.url|urlize }}</dd>
      {% endif %}


      {% if object.is_detail %}

      {% if object.contact_name %}
      <dt>{% trans "Contact" %}</dt>
      <dd>{{ object.contact_name }}</dd>
      {% endif %}

      {% if object.contact_email %}
      <dt>{% trans "Email" %}</dt>
      <dd>{{ object.contact_email|urlize }}</dd>
      {% endif %}

      {% if object.contact_phone %}
      <dt>{% trans "Phone" %}</dt>
      <dd>{{ object.contact_phone|phone2numeric }}</dd>
      {% endif %}

      {% if object.ticket_price %}
      <dt>{% trans "Admission" %}</dt>
      <dd>{{ object.ticket_price }}</dd>
      {% endif %}

      {% if object.ticket_vendor %}
      <dt>{% trans "Tickets available from" %}</dt>
      <dd>{{ object.ticket_vendor|linebreaksbr }}</dd>
      {% endif %}

      {% endif %}

  </dl>

  {% if is_detail %}
  {% include "activities/includes/map.html" with css_class="pb-1" %}
  {% endif %}

  {% with user|is_oembed_url:object.url as is_oembed %}
  {% include "activities/includes/oembed.html" %}
  {% endwith %}
  {% include "activities/includes/description.html" %}

  {% if object.is_canceled %}
</div>
{% endif %}

{% endwith %}
{% endblock content %}

{% block actions %}{% include "events/includes/actions.html" %}{% endblock %}
{% block info %}{% include "events/includes/info.html" %}{% endblock %}
{% block links %}{% include "events/includes/links.html" %}{% endblock %}

templates/events/includes/event_pinned.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/activity_pinned_base.html" %}

{% block actions %}{% include "events/includes/actions.html" %}{% endblock %}

templates/events/includes/info.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/info.html" %}

{% load i18n %}

{% block extra_info %}
{% if object.num_attendees and not object.canceled %}
<div class="info">
  {% if object.has_ended %}
  {% blocktrans count counter=object.num_attendees %}
  1 Attended
  {% plural %}
  {{ counter }} Attended
  {% endblocktrans %}
  {% else %}
  {% blocktrans count counter=object.num_attendees %}
  1 Attending
  {% plural %}
  {{ counter }} Attending
  {% endblocktrans %}
  {% endif %}
</div>
{% endif %}
{% endblock %}

templates/events/includes/links.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/links.html" %}

{% load i18n %}

{% block extra_links %}
{% if object.has_map and not is_detail %}
<a class="text-sm" href="{{ object.get_absolute_url }}#map-for-event-{{ object.id }}">{% trans "Map" %}</a>
{% endif %}
{% endblock %}