localhub/bookmarks/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from .views import (
    bookmarks_comment_list_view,
    bookmarks_message_list_view,
    bookmarks_stream_view,
)

app_name = "bookmarks"

urlpatterns = [
    path("", bookmarks_stream_view, name="activities"),
    path("comments/", bookmarks_comment_list_view, name="comments"),
    path("messages/", bookmarks_message_list_view, name="messages"),
]

localhub/comments/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from . import views

app_name = "comments"


urlpatterns = [
    path("", views.comment_list_view, name="list"),
    path("<int:pk>/", views.comment_detail_view, name="detail"),
    path("<int:pk>/~update/", views.comment_update_view, name="update"),
    path("<int:pk>/~delete/", views.comment_delete_view, name="delete"),
    path("<int:pk>/~like/", views.comment_like_view, name="like"),
    path("<int:pk>/~bookmark/", views.comment_bookmark_view, name="bookmark"),
    path(
        "<int:pk>/~bookmark/remove/",
        views.comment_remove_bookmark_view,
        name="remove_bookmark",
    ),
    path("<int:pk>/~dislike/", views.comment_dislike_view, name="dislike"),
    path("<int:pk>/~flag/", views.comment_flag_view, name="flag"),
    path("<int:pk>/~reply/", views.comment_reply_view, name="reply"),
]

localhub/flags/urls.py
# Django
from django.urls import path

# Local
from .views import flag_delete_view, flag_list_view

app_name = "flags"


urlpatterns = [
    path("", view=flag_list_view, name="list"),
    path("<int:pk>/~delete/", view=flag_delete_view, name="delete"),
]

localhub/likes/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from .views import liked_comment_list_view, liked_stream_view

app_name = "likes"

urlpatterns = [
    path("", liked_stream_view, name="activities"),
    path("comments/", liked_comment_list_view, name="comments"),
]

localhub/users/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path, re_path

# Local
from . import views

app_name = "users"

USERNAME_RE = r"^(?P<username>[\w.@+-]+)/"


def user_re_path(path, *args, **kwargs):
    return re_path(USERNAME_RE + path, *args, **kwargs)


urlpatterns = [
    path("autocomplete/", views.user_autocomplete_list_view, name="autocomplete_list"),
    path("members/", views.member_list_view, name="member_list"),
    path("following/", views.following_user_list_view, name="following_list"),
    path("followers/", views.follower_user_list_view, name="follower_list"),
    path("blocked/", views.blocked_user_list_view, name="blocked_list"),
    user_re_path(r"likes/$", views.user_activity_likes_view, name="activity_likes"),
    user_re_path(
        r"likes/comments/$", views.user_comment_likes_view, name="comment_likes",
    ),
    user_re_path(
        r"mentions/$", views.user_activity_mentions_view, name="activity_mentions",
    ),
    user_re_path(
        r"mentions/comments/$",
        views.user_comment_mentions_view,
        name="comment_mentions",
    ),
    user_re_path(r"preview/$", views.user_preview_view, name="preview"),
    user_re_path(r"follow/$", views.user_follow_view, name="follow"),
    user_re_path(r"unfollow/$", views.user_unfollow_view, name="unfollow"),
    user_re_path(r"block/$", views.user_block_view, name="block"),
    user_re_path(r"unblock/$", views.user_unblock_view, name="unblock"),
    user_re_path(r"comments/$", views.user_comment_list_view, name="comments"),
    user_re_path(r"messages/$", views.user_message_list_view, name="messages"),
    user_re_path(r"$", views.user_stream_view, name="activities"),
]

localhub/comments/forms.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django import forms
from django.utils.translation import gettext_lazy as _

# Local
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        labels = {"content": _("Comment")}

localhub/bookmarks/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Localhub
from localhub.activities.views.streams import BaseActivityStreamView
from localhub.comments.views import BaseCommentListView
from localhub.private_messages.views import (
    BaseMessageListView,
    SenderOrRecipientQuerySetMixin,
)
from localhub.views import SearchMixin


class BookmarksStreamView(SearchMixin, BaseActivityStreamView):
    template_name = "bookmarks/activities.html"
    ordering = ("-bookmarked", "-created")

    def filter_queryset(self, queryset):
        qs = (
            super()
            .filter_queryset(queryset)
            .published_or_owner(self.request.user)
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
        )
        if self.search_query:
            qs = qs.search(self.search_query)
        return qs


bookmarks_stream_view = BookmarksStreamView.as_view()


class BookmarksMessageListView(SenderOrRecipientQuerySetMixin, BaseMessageListView):
    template_name = "bookmarks/messages.html"

    def get_queryset(self):
        qs = (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )
        if self.search_query:
            qs = qs.search(self.search_query)
        return qs


bookmarks_message_list_view = BookmarksMessageListView.as_view()


class BookmarksCommentListView(SearchMixin, BaseCommentListView):
    template_name = "bookmarks/comments.html"

    def get_queryset(self):
        qs = (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_common_annotations(self.request.user, self.request.community)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )
        if self.search_query:
            qs = qs.search(self.search_query)
        return qs


bookmarks_comment_list_view = BookmarksCommentListView.as_view()

localhub/comments/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.conf import settings
from django.db import IntegrityError
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, ListView

# Third Party Libraries
from rules.contrib.views import PermissionRequiredMixin

# Localhub
from localhub.bookmarks.models import Bookmark
from localhub.communities.views import CommunityRequiredMixin
from localhub.flags.views import BaseFlagCreateView
from localhub.likes.models import Like
from localhub.views import (
    ParentObjectMixin,
    SearchMixin,
    SuccessActionView,
    SuccessCreateView,
    SuccessDeleteView,
    SuccessUpdateView,
)

# Local
from .forms import CommentForm
from .models import Comment


class CommentQuerySetMixin(CommunityRequiredMixin):
    def get_queryset(self):
        return Comment.objects.for_community(self.request.community).select_related(
            "owner", "community", "parent", "parent__owner", "parent__community",
        )


class CommentUpdateView(
    PermissionRequiredMixin, CommentQuerySetMixin, SuccessUpdateView,
):
    form_class = CommentForm
    model = Comment
    permission_required = "comments.change_comment"
    success_message = _("Your %(model)s has been updated")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["content_object"] = self.object.get_content_object()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.editor = self.request.user
        self.object.edited = timezone.now()
        self.object.save()

        self.object.notify_on_update()
        return self.success_response()


comment_update_view = CommentUpdateView.as_view()


class CommentFlagView(
    PermissionRequiredMixin, CommentQuerySetMixin, BaseFlagCreateView
):
    permission_required = "comments.flag_comment"
    success_message = _("This comment has been flagged to the moderators")

    def get_parent_queryset(self):
        return (
            super()
            .get_queryset()
            .with_has_flagged(self.request.user)
            .exclude(has_flagged=True)
        )

    def get_permission_object(self):
        return self.parent


comment_flag_view = CommentFlagView.as_view()


class CommentReplyView(
    CommentQuerySetMixin, PermissionRequiredMixin, ParentObjectMixin, SuccessCreateView,
):
    permission_required = "comments.reply_to_comment"
    model = Comment
    form_class = CommentForm
    success_message = _("You have replied to this %(model)s")

    def get_permission_object(self):
        return self.parent

    def get_parent_queryset(self):
        return self.get_queryset()

    @cached_property
    def content_object(self):
        return self.parent.get_content_object()

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["content"].label = _("Reply")
        return form

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["content_object"] = self.content_object
        return data

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.parent = self.parent
        self.object.content_object = self.content_object
        self.object.owner = self.request.user
        self.object.community = self.request.community
        self.object.save()

        self.object.notify_on_create()

        return self.success_response()


comment_reply_view = CommentReplyView.as_view()


class BaseCommentListView(CommentQuerySetMixin, ListView):
    paginate_by = settings.DEFAULT_PAGE_SIZE

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_common_annotations(self.request.user, self.request.community)
            .exclude_blocked_users(self.request.user)
            .exclude_deleted()
            .with_common_related()
        )


class CommentListView(SearchMixin, BaseCommentListView):

    template_name = "comments/comment_list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by("-created")


comment_list_view = CommentListView.as_view()


class CommentDetailView(CommentQuerySetMixin, DetailView):
    model = Comment

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_common_annotations(self.request.user, self.request.community)
            .exclude_deleted(self.request.user)
            .with_common_related()
        )

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.object.get_notifications().for_recipient(
            self.request.user
        ).unread().update(is_read=True)
        return response

    def get_flags(self):
        return (
            self.object.get_flags()
            .select_related("user", "community")
            .prefetch_related("content_object")
            .order_by("-created")
        )

    def get_replies(self):
        if self.object.deleted:
            return self.get_queryset().none()
        return self.get_queryset().filter(parent=self.object).order_by("created")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.user.has_perm(
            "communities.moderate_community", self.request.community
        ):

            data["flags"] = self.get_flags()
        data.update(
            {
                "replies": self.get_replies(),
                "content_object": self.object.get_content_object(),
            }
        )
        return data


comment_detail_view = CommentDetailView.as_view()


class BaseCommentActionView(CommentQuerySetMixin, SuccessActionView):
    ...


class BaseCommentBookmarkView(PermissionRequiredMixin, BaseCommentActionView):
    permission_required = "comments.bookmark_comment"
    is_success_ajax_response = True
    success_template_name = "comments/includes/bookmark.html"


class CommentBookmarkView(BaseCommentBookmarkView):
    success_message = _("You have bookmarked this comment")

    def post(self, request, *args, **kwargs):
        try:
            Bookmark.objects.create(
                user=request.user,
                community=request.community,
                content_object=self.object,
            )
        except IntegrityError:
            pass
        return self.success_response()

    def get_success_context_data(self):
        return {**super().get_success_context_data(), "has_bookmarked": True}


comment_bookmark_view = CommentBookmarkView.as_view()


class CommentRemoveBookmarkView(BaseCommentBookmarkView):
    success_message = _("You have removed this comment from your bookmarks")

    def post(self, request, *args, **kwargs):
        Bookmark.objects.filter(user=request.user, comment=self.object).delete()
        return self.success_response()

    def delete(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_context_data(self):
        return {**super().get_success_context_data(), "has_bookmarked": False}


comment_remove_bookmark_view = CommentRemoveBookmarkView.as_view()


class BaseCommentLikeView(PermissionRequiredMixin, BaseCommentActionView):
    permission_required = "comments.like_comment"
    is_success_ajax_response = True
    success_template_name = "comments/includes/like.html"


class CommentLikeView(BaseCommentLikeView):
    success_message = _("You have liked this comment")

    def post(self, request, *args, **kwargs):
        try:
            Like.objects.create(
                user=request.user,
                community=request.community,
                recipient=self.object.owner,
                content_object=self.object,
            ).notify()
        except IntegrityError:
            pass
        return self.success_response()

    def get_success_context_data(self):
        return {**super().get_success_context_data(), "has_liked": True}


comment_like_view = CommentLikeView.as_view()


class CommentDislikeView(BaseCommentLikeView):
    success_message = _("You have stopped liking this comment")

    def post(self, request, *args, **kwargs):
        Like.objects.filter(user=request.user, comment=self.object).delete()
        return self.success_response()

    def delete(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_success_context_data(self):
        return {**super().get_success_context_data(), "has_liked": False}


comment_dislike_view = CommentDislikeView.as_view()


class CommentDeleteView(
    PermissionRequiredMixin, CommentQuerySetMixin, SuccessDeleteView,
):
    permission_required = "comments.delete_comment"
    template_name = "comments/comment_confirm_delete.html"
    success_message = _("You have deleted this comment")

    def get_success_url(self):
        obj = self.object.get_content_object()
        if obj:
            return obj.get_absolute_url()
        return reverse("comments:list")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user != self.object.owner:
            self.object.soft_delete()
            self.object.notify_on_delete(self.request.user)
        else:
            self.object.delete()

        return self.success_response()


comment_delete_view = CommentDeleteView.as_view()

localhub/likes/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Localhub
from localhub.activities.views.streams import BaseActivityStreamView
from localhub.comments.views import BaseCommentListView


class LikedStreamView(BaseActivityStreamView):
    template_name = "likes/activities.html"
    ordering = ("-liked", "-created")

    def get_count_queryset_for_model(self, model):
        return self.filter_queryset(model.objects.liked(self.request.user))

    def filter_queryset(self, queryset):
        return (
            super()
            .filter_queryset(queryset)
            .liked(self.request.user)
            .with_liked_timestamp(self.request.user)
        )


liked_stream_view = LikedStreamView.as_view()


class LikedCommentListView(BaseCommentListView):
    template_name = "likes/comments.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .liked(self.request.user)
            .with_common_annotations(self.request.user, self.request.community)
            .with_liked_timestamp(self.request.user)
            .order_by("-liked", "-created")
        )


liked_comment_list_view = LikedCommentListView.as_view()

templates/comments/includes/bookmark.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if has_bookmarked %}
<a href="{% url 'comments:remove_bookmark' object.id %}"
   class="dropdown-menu-item line-through"
   data-turbolinks="false"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Bookmark" %}</a>
{% else %}
<a href="{% url 'comments:bookmark' object.id %}"
   class="dropdown-menu-item"
   data-turbolinks="false"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Bookmark" %}</a>
{% endif %}

templates/comments/includes/comment.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load account %}
{% load rules %}
{% load users %}

{% has_perm "communities.moderate_community" user community as can_moderate_community %}

<article class="card {% if css_class %} {{ css_class }}{% endif %} {% if comment.is_blocked %} bg-gray-100{% endif %}"
         role="comment"
         data-controller="clipboard"
         data-clipboard-message="{% trans 'Markdown content has been copied' %}"
         id="comment-{{ comment.id }}">
  <div class="mb-3">
    {% if include_content_object %}
    <div class="flex flex-wrap items-center mb-3">
      {% if content_object %}
      <a class="inline-block font-semibold mr-2"
         href="{{ content_object.get_absolute_url }}">{{ content_object }}</a>
      <a class="tag hover:text-gray-300 mr-2"
         href="{{ content_object|resolve_url:"list" }}">{{ content_object|verbose_name|title }}</a>

      {% if can_moderate_community and comment.is_flagged %}
      <span class="tag bg-warning mr-2">{% trans "Flagged" %}</span>
      {% endif %}

      {% if comment.is_new %}
      <span class="tag tag-primary">{% trans "New" %}</span>
      {% endif %}

      {% else %}
      {% trans "[Deleted]" %}
      {% endif %}
      {% if can_moderate_community %}
      {% endif %}
    </div>
    {% endif %}
    <div class="flex flex-wrap items-center">
      {% url 'users:comments' comment.owner.username as owner_url %}
      {% include "includes/timesince.html" with profile_url=owner_url timestamp=comment.created owner=comment.owner css_class="mr-2" %}
      {% if comment.is_blocked %}
      <span class="tag tag-primary">{% trans "Blocked" %}</span>
      {% endif %}
      {% if not include_content_object and can_moderate_community and comment.is_flagged %}
      <span class="tag bg-warning mr-2">{% trans "Flagged" %}</span>
      {% endif %}
    </div>
  </div>
  {% if comment.is_blocked %}
  <div class="mb-3 cursor-pointer"
       data-controller="toggle"
       data-action="click->toggle#toggle">

    <p class="font-semibold p-5 text-center"
       data-target="toggle.togglable">
      {% trans "This comment is hidden because you have blocked this user." %}
    </p>

    <div class="markdown-content hidden"
         data-target="toggle.togglable">
      {{ comment.content.markdown|strip_external_images:user|lazify }}
    </div>

    <div data-target="toggle.togglable text-center align-middle py-3">
      <div class="flex justify-center items-center">
        <button class="btn btn-link w-full text-sm"
                data-action="toggle#toggle">{% trans "Show Comment" %}</button>
      </div>
    </div>
  </div>

  {% else %}
  <div class="mb-3">
    <textarea data-target="clipboard.textarea"
              readonly
              class="hidden">{{ comment.content }}</textarea>
    {% if comment.deleted %}
    <p>{% blocktrans %}This comment has been deleted by a community moderator{% endblocktrans %}</p>
    {% endif %}
    {% if show_content %}
    {% collapsable is_detail %}
    <div class="markdown-content">
      {{ comment.content.markdown|strip_external_images:user|lazify }}
    </div>
    {% endcollapsable %}
    {% endif %}
  </div>
  <div class="card-footer">
    <div class="flex flex-wrap items-center text-xs text-muted mb-3">
      {% if comment.num_likes %}
      <div class="mr-2">
        {{ comment.num_likes }}
        {% blocktrans count counter=comment.num_likes %}
        Like
        {% plural %}
        Likes
        {% endblocktrans %}
      </div>
      {% endif %}

      {% if comment.edited %}
      <div class="">
        {% blocktrans with edited=comment.edited|timesince %}Updated {{ edited }} ago{% endblocktrans %}
      </div>
      {% endif %}
    </div>
    <div class="flex flex-wrap items-center">
      <div class="text-sm mr-2"
           data-controller="dropdown"
           data-action="click@window->dropdown#close keydown@window->dropdown#close">
        <button class="btn btn-dropdown"
                data-action="dropdown#toggle">
          {% trans "Actions..." %}<i class="icon icon-caret"></i>
        </button>
        <div class="dropdown-menu mt-1 hidden"
             data-target="dropdown.menu">
          {% has_perm "comments.like_comment" user comment as can_like_comment %}
          {% if can_like_comment %}
          <div data-controller="ajax"
               data-ajax-replace>
            {% include "comments/includes/like.html" with object=comment has_liked=comment.has_liked %}
          </div>
          {% endif %}

          {% has_perm "comments.bookmark_comment" user comment as can_bookmark_comment %}
          {% if can_bookmark_comment %}
          <div data-controller="ajax"
               data-ajax-replace>
            {% include "comments/includes/bookmark.html" with object=comment has_bookmarked=comment.has_bookmarked %}
          </div>
          {% endif %}

          {% has_perm "comments.reply_to_comment" user comment as can_reply %}
          {% if can_reply %}
          <a class="dropdown-menu-item"
             href="{% url 'comments:reply' comment.id %}#comment-form">{% trans "Reply" %}</a>
          {% endif %}

          {% has_perm "comments.flag_comment" user comment as can_flag_comment %}
          {% if can_flag_comment and not comment.has_flagged %}
          <a class="dropdown-menu-item"
             href="{% url 'comments:flag' comment.id %}">
            {% trans "Flag" %}
          </a>
          {% endif %}
          {% has_perm "comments.change_comment" user comment as can_change_comment %}

          {% if can_change_comment %}
          <a class="dropdown-menu-item"
             href="{% url 'comments:update' comment.id %}#comment-form">
            {% trans "Edit" %}
          </a>
          {% endif %}
          {% has_perm "comments.delete_comment" user comment as can_delete_comment %}
          {% if can_delete_comment %}
          <a href="{% url 'comments:delete' comment.id %}"
             class="dropdown-menu-item"
             data-turbolinks="false"
             data-controller="ajax"
             data-action="ajax#post"
             {% if not is_detail %}
             data-ajax-redirect="{{ request.get_full_path }}"
             {% endif %}
             data-ajax-confirm-header="{% trans 'Delete Comment' %}"
             data-ajax-confirm-body="{% trans 'Are you sure you want to delete this comment?' %}">
            {% trans "Delete" %}
          </a>
          {% endif %}
          {% if not comment.is_blocked %}
          <a href="#"
             class="dropdown-menu-item"
             data-turbolinks="false"
             data-target="clipboard.button"
             data-action="clipboard#copy">
            {% trans "Copy Markdown" %}
          </a>
          {% endif %}
          </ul>
        </div>
      </div>
      <div>
        {% if not is_detail and not comment.deleted %}
        <a class="inline-block text-sm mr-2"
           href="{{ comment.get_absolute_url }}">{% trans "Link" %}</a>
        {% endif %}
        {% if parent %}
        <a class="inline-block text-sm"
           href="{{ parent.get_absolute_url }}">{% trans "Parent" %}</a>
        {% endif %}
      </div>
    </div>
    {% endif %}
</article>

templates/comments/includes/comment_list.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load comments %}

{% if page_obj.number > 1 %}
{% include "includes/pagination.html" with css_class="mb-3" %}
{% endif %}

{% for comment in object_list %}
{% render_comment request user comment include_content_object=True css_class="mt-2" %}
{% empty %}
{% include "includes/empty.html" %}
{% endfor %}
{% include "includes/pagination.html" %}

templates/comments/includes/like.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if has_liked %}
<a href="{% url 'comments:dislike' object.id %}"
   class="dropdown-menu-item line-through"
   data-turbolinks="false"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Like" %}</a>
{% else %}
<a href="{% url 'comments:like' object.id %}"
   class="dropdown-menu-item"
   data-turbolinks="false"
   data-target="ajax.button"
   data-action="ajax#post">{% trans "Like" %}</a>
{% endif %}